---

- name: Create /etc/rc.conf.d if it does not exist
  file:
    path: /etc/rc.conf.d
    mode: 755
    state: directory

- name: Create rc conf flagment
  template:
    src: rc.conf.FreeBSD.j2
    dest: /etc/rc.conf.d/elasticsearch
    mode: 644
  notify:
    - Restart elasticsearch
