---

- name: Create jvm.in
  template:
    src: jvm.in.OpenBSD.j2
    dest: /etc/elasticsearch/jvm.in
    mode: 0644

- name: Add `source` to /etc/elasticsearch/elasticsearch.in.sh
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.in.sh
    insertafter: "^#!/bin/sh"
    line: ". /etc/elasticsearch/jvm.in"
    state: present
