---

- name: Install elasticsearch
  pkgng:
    name: "{{ elasticsearch_package }}"
    state: present

- name: Patch rc script wait_for.patch
  patch:
    src: wait_for.patch
    dest: /usr/local/etc/rc.d/elasticsearch

- name: Patch rc script jps.patch
  patch:
    src: jps.patch
    dest: /usr/local/etc/rc.d/elasticsearch
